/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/calendar/calendar.module';
import * as import2 from '@angular/common';
class CalendarModuleInjector extends import0.ɵNgModuleInjector<import1.CalendarModule> {
  _CommonModule_0:import2.CommonModule;
  _CalendarModule_1:import1.CalendarModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.CalendarModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._CalendarModule_1 = new import1.CalendarModule();
    return this._CalendarModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.CalendarModule)) { return this._CalendarModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CalendarModuleNgFactory:import0.NgModuleFactory<import1.CalendarModule> = new import0.NgModuleFactory<any>(CalendarModuleInjector,import1.CalendarModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovSmVua2lucy93b3Jrc3BhY2UvLWNhbGVuZGFyLWNvbXBvbmVudHNfbWFzdGVyLUJLNEpSV0tBSFlMNTJQNUszNlFaR1U0SzdTQ0xDQk1YSFA0Rzc3TkQyUUVLVldNN0lWRVEvdGhpcmQtcGFydHkvYW5ndWxhci9zcmMvY2FsZW5kYXIvY2FsZW5kYXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0plbmtpbnMvd29ya3NwYWNlLy1jYWxlbmRhci1jb21wb25lbnRzX21hc3Rlci1CSzRKUldLQUhZTDUyUDVLMzZRWkdVNEs3U0NMQ0JNWEhQNEc3N05EMlFFS1ZXTTdJVkVRL3RoaXJkLXBhcnR5L2FuZ3VsYXIvc3JjL2NhbGVuZGFyL2NhbGVuZGFyLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
