/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/calendar/calendar-all.module';
import * as import2 from '@angular/common';
import * as import3 from '../../../src/calendar/calendar.module';
class CalendarAllModuleInjector extends import0.ɵNgModuleInjector<import1.CalendarAllModule> {
  _CommonModule_0:import2.CommonModule;
  _CalendarModule_1:import3.CalendarModule;
  _CalendarAllModule_2:import1.CalendarAllModule;
  __NgLocalization_3:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_3():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_3 == null)) { (this.__NgLocalization_3 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_3;
  }
  createInternal():import1.CalendarAllModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._CalendarModule_1 = new import3.CalendarModule();
    this._CalendarAllModule_2 = new import1.CalendarAllModule();
    return this._CalendarAllModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.CalendarModule)) { return this._CalendarModule_1; }
    if ((token === import1.CalendarAllModule)) { return this._CalendarAllModule_2; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CalendarAllModuleNgFactory:import0.NgModuleFactory<import1.CalendarAllModule> = new import0.NgModuleFactory<any>(CalendarAllModuleInjector,import1.CalendarAllModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovSmVua2lucy93b3Jrc3BhY2UvLWNhbGVuZGFyLWNvbXBvbmVudHNfbWFzdGVyLUJLNEpSV0tBSFlMNTJQNUszNlFaR1U0SzdTQ0xDQk1YSFA0Rzc3TkQyUUVLVldNN0lWRVEvdGhpcmQtcGFydHkvYW5ndWxhci9zcmMvY2FsZW5kYXIvY2FsZW5kYXItYWxsLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9KZW5raW5zL3dvcmtzcGFjZS8tY2FsZW5kYXItY29tcG9uZW50c19tYXN0ZXItQks0SlJXS0FIWUw1MlA1SzM2UVpHVTRLN1NDTENCTVhIUDRHNzdORDJRRUtWV003SVZFUS90aGlyZC1wYXJ0eS9hbmd1bGFyL3NyYy9jYWxlbmRhci9jYWxlbmRhci1hbGwubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
