/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/calendar/calendar.component';
import * as import2 from '@angular/forms';
const styles_CalendarComponent:any[] = ([] as any[]);
export const RenderType_CalendarComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CalendarComponent,
  data: {}
}
);
export function View_CalendarComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(2,([] as any[]),(null as any),(null as any));
}
function View_CalendarComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'ej-calendar',([] as any[]),(null as any),(null as any),(null as any),View_CalendarComponent_0,RenderType_CalendarComponent)),
    import0.ɵdid(3268608,(null as any),0,import1.CalendarComponent,[import0.ElementRef],(null as any),(null as any)),
    import0.ɵprd(2560,(null as any),import2.NG_VALUE_ACCESSOR,(p0_0:any) => {
      return [p0_0];
    },[import1.CalendarComponent])
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const CalendarComponentNgFactory:import0.ComponentFactory<import1.CalendarComponent> = import0.ɵccf('ej-calendar',import1.CalendarComponent,View_CalendarComponent_Host_0,{
  depth: 'depth',
  enablePersistence: 'enablePersistence',
  enableRtl: 'enableRtl',
  firstDayOfWeek: 'firstDayOfWeek',
  locale: 'locale',
  max: 'max',
  min: 'min',
  start: 'start',
  value: 'value',
  weekNumber: 'weekNumber'
}
,{
  change: 'change',
  created: 'created',
  destroyed: 'destroyed',
  navigated: 'navigated',
  renderDayCell: 'renderDayCell',
  valueChange: 'valueChange'
}
,([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovSmVua2lucy93b3Jrc3BhY2UvLWNhbGVuZGFyLWNvbXBvbmVudHNfbWFzdGVyLUJLNEpSV0tBSFlMNTJQNUszNlFaR1U0SzdTQ0xDQk1YSFA0Rzc3TkQyUUVLVldNN0lWRVEvdGhpcmQtcGFydHkvYW5ndWxhci9zcmMvY2FsZW5kYXIvY2FsZW5kYXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0plbmtpbnMvd29ya3NwYWNlLy1jYWxlbmRhci1jb21wb25lbnRzX21hc3Rlci1CSzRKUldLQUhZTDUyUDVLMzZRWkdVNEs3U0NMQ0JNWEhQNEc3N05EMlFFS1ZXTTdJVkVRL3RoaXJkLXBhcnR5L2FuZ3VsYXIvc3JjL2NhbGVuZGFyL2NhbGVuZGFyLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L0plbmtpbnMvd29ya3NwYWNlLy1jYWxlbmRhci1jb21wb25lbnRzX21hc3Rlci1CSzRKUldLQUhZTDUyUDVLMzZRWkdVNEs3U0NMQ0JNWEhQNEc3N05EMlFFS1ZXTTdJVkVRL3RoaXJkLXBhcnR5L2FuZ3VsYXIvc3JjL2NhbGVuZGFyL2NhbGVuZGFyLmNvbXBvbmVudC50cy5DYWxlbmRhckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxlai1jYWxlbmRhcj48L2VqLWNhbGVuZGFyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7Z0JBQUE7Z0JBQUE7TUFBQTtJQUFBOzs7SUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
